#开发环境

server:
  port: 8443 #服务器端口
  ssl:
    key-store: keystore.p12
    key-store-password: 111111
    key-store-type: PKCS12
    key-alias: tomcat

#thymeleaf模板不设置缓存
spring:
  thymeleaf:
    cache: false